// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/gofiber/fiber/v2"
	"hr-leave-request/config"
	"hr-leave-request/handlers"
	"hr-leave-request/repositories"
	"hr-leave-request/services"
)

// Injectors from wire.go:

func InitializeApp() (*fiber.App, error) {
	applicationConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	db, err := config.NewDatabase(applicationConfig)
	if err != nil {
		return nil, err
	}
	employeeRepository := repositories.NewEmployeeRepository(db)
	employeeService := services.NewEmployeeService(employeeRepository)
	employeeHandler := handlers.NewEmployeeHandler(employeeService)
	app := NewFiberApp(employeeHandler)
	return app, nil
}

// wire.go:

func NewFiberApp(employeeHandler *handlers.EmployeeHandler) *fiber.App {
	app := fiber.New(fiber.Config{
		AppName: "HR Leave Request API",
	})
	handlers.SetupRoutes(app, employeeHandler)

	return app
}
